### PR TITLE
Update index with Mentors.html

### PR DESCRIPTION
**Pull request by aryang23**
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>codeforcause.org</title>
    <style type="text/css">
      html, body {
        height: 100%;
      }
      body {
        background-color: #fff;
        background: radial-gradient(circle at center, #fff 0%, #f8f8f8 75%, #ebebeb 100%);
        color: #222;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
        font-size: 1rem;
        line-height: 1.5;
        margin: 0;
        display: flex;
        justify-content: center;
        align-items: center;
      }
      main {
        padding: 1rem;
        text-align: center;
      }
      h1 {
        font-size: 2.5rem;
        line-height: 1.1;
        margin: 0;
      }
      @media screen and (max-width: 480px) {
        h1 {
          font-size: 1.5rem;
        }
      }
      h1::after {
        content: "";
        background-color: #ffe800;
        background: repeating-linear-gradient(45deg, #ffe800, #ffe800 0.5rem, #222 0.5rem, #222 1.0rem);
        display: block;
        height: 0.5rem;
        margin-top: 1rem;
      }
      p {
        margin: 1rem 0 0 0;
        font-weight: bold;
      }
      div{
          margin-left: 700px;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>codeforcause.org</h1>
      <p>Our website is under construction.</p>
      <p>We are coming very soon.</p>
      <br><br>
      
      
      
      
      
      <br><br>
      <div>
          <h2>Our Mentors: -</h2>
          <ul>
              <li>Anuj Garg</li>
              <li>Gaurav Beriwal</li>
              <li>Kunal Kushwaha</li>
              <li>Ekta Mishra</li>
              <li>Ganga Chaturvedi</li>
              <li>Bharat Bhardwaj</li>
          </ul>
        </div>
        <p>Just Wait and Watch :)</p>
    </main>
  </body>
</html>

### CODE REVIEW

**Comment by aryang23** [comment]
If You also want to add the name of the mentors, then this will be the best for You.

**Comment by Abhishek-kumar09** [comment]
@aryang23 Thanks for your PR.
This repo was an alternative to the website under progress.
Since we have done things up to the extend that we can show it to the public, we have published the actual website https://codeforcause.org
I think repo is of no use right now.

But yes we are surely welcoming you to learn something from us and our webinars and contribute to other codeforcause projects on the way.

contribute to website repo: https://github.com/codeforcauseorg/codeforcause.org

**Comment by aryang23** [comment]
Sir need Your help, Can You Please share some good resources and good projects where I can practice so as to make these https://codeforcause.org   kinda websites. With Proper FrontEnd and BackEnd.
I have basically completed the course and would love to do projects or work with a team to learn how to make.

Waiting For Your Reply.

**Comment by aryang23** [comment]
Sir need Your help,
Can You Please share some good resources and good projects where I can
practice so as to make these https://codeforcause.org kinda websites.
With Proper FrontEnd and BackEnd.
I have basically completed the course and would love to do projects or work
with a team to learn how to make.

**Comment by Abhishek-kumar09** [comment]
Hello @aryang23 ,
If you are a learner, making a website should be done entirely by you from scratch using any technology you have learnt may it be react, node, django flask, anything.
 ofcourse you could seek help from our community on discord, telegram, etc. There are lots and lots of devlopers there to help each other.

> Can You Please share some good resources and good projects where I can
practice so as to make these codeforcause.org kinda websites.
With Proper FrontEnd and BackEnd.

Tbh, making a full fledged website requires skills from multiple verse, frontend, designing, backend, serving, and so on. You can reach through these phases one by one, take help from google and community. The internet is full of resources.

They will surely ehelp you:
Discussions: https://t.me/codeforcausechat
Discord: https://discord.gg/sZfpv7W

**Pull request closed without merging**
